# Generated by Django 4.2.7 on 2026-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_time',
            field=models.CharField(blank=True, default='7', help_text='Délai de livraison (ex: 3-5 jours)', max_length=50),
        ),
    ]
