# Generated by Django 4.2.7 on 2026-05-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_bl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
    ]
