# Generated by Django 4.2.7 on 2026-05-03 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_address', models.JSONField(default=dict)),
                ('billing_address', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_accepted', models.BooleanField(default=False)),
                ('warranty_vehicle_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_vehicle_mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('cri_amount_paid', models.DecimalField(decimal_places=3, default=0, help_text='Amount paid now via CRI', max_digits=10)),
                ('cri_remaining', models.DecimalField(decimal_places=3, default=0, help_text='Remaining unpaid amount (loan)', max_digits=10)),
                ('cri_remarque', models.TextField(blank=True, help_text='CRI payment note', null=True)),
                ('transfer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_image', models.CharField(blank=True, max_length=500, null=True)),
                ('transfer_amount_paid', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('transfer_remaining', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('transfer_remarque', models.TextField(blank=True, null=True)),
                ('lettre_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lettre_date', models.DateField(blank=True, null=True)),
                ('lettre_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lettre_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lettre_rib', models.CharField(blank=True, max_length=100, null=True)),
                ('lettre_lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('lettre_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lettre_image', models.CharField(blank=True, max_length=500, null=True)),
                ('lettre_amount_paid', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('lettre_remaining', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('lettre_remarque', models.TextField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_image', models.CharField(blank=True, max_length=500, null=True)),
                ('cheque_amount_paid', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cheque_remaining', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cheque_remarque', models.TextField(blank=True, null=True)),
                ('cod_authorization_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_amount_paid', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cod_remaining', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cod_remarque', models.TextField(blank=True, null=True)),
                ('commercial', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('total_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmé', 'Confirmé'), ('livré', 'Livré')], default='en_attente', max_length=20)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('urgent', 'Urgent')], default='normale', max_length=20)),
                ('supplier', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('dot', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('specifications', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('transporteur', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('prepare', 'En préparation'), ('en_route', 'En route'), ('livre', 'Livré')], default='prepare', max_length=20)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('colis', models.IntegerField(default=1)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='CRIBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, default=0, help_text='Total unpaid CRI amount carried over from previous orders', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cri_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
