# Generated by Django 4.2.7 on 2026-05-21 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_delivery_numero_suivi_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField(blank=True, null=True)),
                ('order_item_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('order_ref', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('mileage_at_purchase', models.CharField(blank=True, max_length=50)),
                ('current_mileage', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('invoice_photo', models.FileField(blank=True, null=True, storage=orders.models._sav_storage, upload_to='sav/invoices/')),
                ('tire_video', models.FileField(blank=True, null=True, storage=orders.models._sav_storage, upload_to='sav/videos/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('resolved', 'Resolu'), ('rejected', 'Rejete')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
