# Generated by Django 4.2.7 on 2026-05-21 21:21

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_warrantyclaimtireimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='invoice_photo',
            field=models.FileField(blank=True, null=True, storage=orders.models._sav_storage, upload_to='sav/invoices/'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='tire_video',
            field=models.FileField(blank=True, null=True, storage=orders.models._sav_storage, upload_to='sav/videos/'),
        ),
    ]
