# Generated by Django 4.2.7 on 2026-05-03 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échoué')], default='queued', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('images_processed', models.BooleanField(default=False)),
                ('errors', models.JSONField(default=list)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Montant total')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix')),
                ('old_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Ancien prix')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image principale')),
                ('image_2', models.URLField(blank=True, null=True, verbose_name='Image 2')),
                ('image_3', models.URLField(blank=True, null=True, verbose_name='Image 3')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Taille')),
                ('season', models.CharField(blank=True, choices=[('summer', 'Été'), ('winter', 'Hiver'), ('all_season', '4 saisons')], max_length=20, verbose_name='Saison')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_min', models.PositiveIntegerField(default=5, verbose_name='Stock minimum (alerte)')),
                ('stock_max', models.PositiveIntegerField(default=100, verbose_name='Stock maximum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('designation', models.CharField(blank=True, max_length=255, verbose_name='Désignation')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emplacement')),
                ('fabrication_date', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='PneuShop Tunisia', max_length=255)),
                ('description', models.TextField(default='Votre spécialiste en pneumatiques')),
                ('adresse', models.TextField(default='Avenue Habib Bourguiba, Tunis')),
                ('telephone', models.CharField(default='+216 71 123 456', max_length=20)),
                ('email', models.EmailField(default='contact@pneushop.tn', max_length=254)),
                ('horaires', models.CharField(default='Lun-Sam: 8h-18h', max_length=255)),
                ('email_commandes', models.BooleanField(default=True)),
                ('email_stock', models.BooleanField(default=True)),
                ('sms_clients', models.BooleanField(default=False)),
                ('push_admin', models.BooleanField(default=True)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('mot_de_passe_force', models.BooleanField(default=True)),
                ('authentification_double', models.BooleanField(default=False)),
                ('journalisation', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('sauvegarde_auto', models.BooleanField(default=True)),
                ('langue_principale', models.CharField(default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
