# Generated by Django 4.2.7 on 2026-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images_processed_integerfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='created_names',
            field=models.JSONField(default=list),
        ),
    ]
