# Generated by Django 4.2.7 on 2026-05-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorderitem_dot_emplacement'),
        ('products', '0004_product_promotion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantite restante')),
                ('dot', models.CharField(blank=True, max_length=20, verbose_name='DOT (sem.annee)')),
                ('dot_date', models.DateField(blank=True, null=True, verbose_name='Date approximative du DOT')),
                ('emplacement', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recu le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='products.product', verbose_name='Produit')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='purchases.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Lot de stock (DOT)',
                'verbose_name_plural': 'Lots de stock (DOT)',
                'ordering': ['dot_date', 'created_at'],
            },
        ),
    ]
