# Generated by Django 4.2.7 on 2026-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockbatch_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Prix d'achat"),
        ),
    ]
