# Generated by Django 4.2.7 on 2026-06-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.importjob', verbose_name="Fichier d'import"),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Téléversé'), ('queued', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échoué')], default='queued', max_length=20),
        ),
    ]
